server:
  port: 8082
  servlet:
    context-path: /
spring:
  application:
    name: VendingMachineApi
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
      ddl-auto: update
    properties:
      hibernate:
        generate_statistics: true
        format_sql: true
        show-sql: true
    h2:
      console:
        enabled: true
        path: '/h2-console'
        settings:
          trace: true
          web-allow-others: true
  flyway:
    url: jdbc:h2:mem:mydb
    user: sa
    password:

logging:
  level:
    org:
      hibernate:
        stat: debug
        type: trace
