package com.vending.api.utils

object ConstantUtils {
    const val INVALID_PRODUCT_ID = "Invalid product Id"
    const val USER_CREATED_SUCCESSFULLY = "User created successfully"
    const val ID_NOT_NULL = "Id cannot be null"
    const val TOKEN_FAIL = "Failed to generate new token"
    const val INVALID_USER_PLEASE_LOGIN = "Invalid user, please login"
    const val ACCESS_DENIED = "Oops, you do not have access to this resource"
    const val PASSWORD_MISMATCH = "Password mismatch"
    const val INVALID_REFRESH_TOKEN = "Invalid refresh token"
    const val USERNAME_ALREADY_EXIST = "Username already exist"
    const val COULD_NOT_RETRIEVE_LOGIN_USER = "Could not retrieve login user"
    const val PRODUCT_CREATED_SUCCESSFULLY = "Product created successfully"
    const val PRODUCT_UPDATED_SUCCESSFULLY = "Product updated successfully"
    const val COULD_NOT_RETRIEVE_PRODUCT = "Could not retrieve product with the provided Id"
    const val COULD_NOT_RETRIEVE_USER = "Could not retrieve user with the provided Id"
    const val SUCCESS = "Success"
    const val PRODUCT_RETRIEVED = "Product retrieved successfully"
    const val PRODUCT_NOT_FOUND = "Product not found"
    const val INVALID_REQUEST_PAYLOAD = "Invalid request payload"
    const val INVALID_PARAMETERS = "Invalid parameters"
    const val PARAMETER_MISSING = " parameter is missing"
    const val MEDIA_NOT_SUPPORT = " media type is not supported. Supported media types are "
    const val ERROR_WRITING_JSON = "Error writing JSON output"
    const val DATABASE_ERROR = "Database error"
    const val INVALID_DATA = "Invalid input data"
    const val ERROR_PLEASE_TRY_AGAIN = "Error!, please try again"
    const val CONNECTION_ERROR = "Connection error, please try again"
    const val BAD_CREDENTIALS = "Bad credentials"
    const val USERNAME_NOT_FOUND = "Username not found!"
    const val INSUFFICIENT_AUTHENTICATION = "Insufficient authentication"
    const val NULL_ERROR = "Null erro! Please try again"
    const val INVALID_NUMBER_FORMAT = "Invalid Number format"
    const val ENTITY_EXISTS = "Entity data already exist"
    const val API_TIMEOUT = "Api timeout"
    const val USER_UPDATED_SUCCESSFULLY = "User updated successfully"
    const val DEPOSIT_SUCCESSFUL = "Deposit successful"
    const val DEPOSIT_RESET_SUCCESSFUL = "Deposit reset successful"
    const val INSUFFICIENT_DEPOSIT = "Insufficient deposit"
}